language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install python-dev python-pip python-pyexiv2 libimage-exiftool-perl -y"
install:
  - "sudo pip install docopt LatLon mock nose requests send2trash"
# command to run tests
# test mapquest key
before_script:
  - "mkdir ~/.elodie"
  - "sed 's/your-api-key-goes-here/x8wQLqGhW7qK3sFpjYtVTogVtoMK0S8s/g' config.ini-sample > ~/.elodie/config.ini"
script: "nosetests -w elodie/tests"
